version: '3'

services:
  web:
    build: .
    image: nodejs
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: /usr/src/app/node_modules/.bin/nodemon server.js

volumes:
  node_modules: